### ISSUE TITLE
Emulated device not displaying history

### ISSUE THREAD

**Issue by virgesmith** [disruptive-technologies/python-client#71]
I'm trying to upload historical data to an emulated humidity sensor, but finding that I can't see the data in DT studio. Here's a reproducible example that creates a device, sends some timestamped events, then retrieves and lists the device's event history:

```
import os
import disruptive as dt
from datetime import datetime, timedelta, timezone
from dotenv import load_dotenv
from time import sleep
load_dotenv()

_KEY_ID = os.getenv('DT_SVC_KEY', '')
_SECRET = os.getenv('DT_SVC_SECRET', '')
_EMAIL = os.getenv('DT_SVC_EMAIL', '')
_PROJECT_ID = os.getenv('DT_PROJECT', '')

dt.default_auth = dt.Auth.service_account(_KEY_ID, _SECRET, _EMAIL)

vsensor = dt.Emulator.create_device(_PROJECT_ID, dt.Device.HUMIDITY, display_name="test_timestamp")

device_id = vsensor.device_id
print(device_id)

# publish some historic events
for i in range(5):
  timestamp = datetime.now(tz=timezone.utc) - timedelta(minutes=10-i) #(tz=timezone.utc)
  dt.Emulator.publish_event(device_id, _PROJECT_ID, data=dt.events.Humidity(celsius=20.0+i, humidity=50.0+i, timestamp=timestamp))

# wait...
sleep(5)

#now get events back
event_history = dt.EventHistory.list_events(device_id, _PROJECT_ID)

for e in event_history:
  print(e.event_type, str(e.data.timestamp))

```
which produces something like:

```
emuc3bdu268l9ck9sfrm9tg
networkStatus 2021-06-26 08:02:17.111216+00:00
networkStatus 2021-06-26 08:02:16.927892+00:00
networkStatus 2021-06-26 08:02:16.746447+00:00
networkStatus 2021-06-26 08:02:16.561380+00:00
networkStatus 2021-06-26 08:02:16.394273+00:00
humidity 2021-06-26 07:56:16.984021+00:00
humidity 2021-06-26 07:55:16.796853+00:00
humidity 2021-06-26 07:54:16.621677+00:00
humidity 2021-06-26 07:53:16.448767+00:00
humidity 2021-06-26 07:52:16.280573+00:00
```
note the networkStatus events (with different timestamps)

and what I see in DT studio is the latest value (as expected) in the top box, but the event history is empty, whatever I try, so I cant actually view the data I sent.

NB if I send current events, I don't get this problem

Update: I also get this behaviour using the emulator API directly

**Comment by vegather** [comment]
@virgesmith Like you suggested, this is a bug related to how the emulator generates the `NetworkStatus` events. All events published to the emulator (except `NetworkStatus` and Cloud Connector events) gets an associated `NetworkStatus` event. DT Studio uses these events to display when the sensor was offline. The bug here is basically that the `timestamp` you've specified in the `Humidity` event is not considered when generating the associated `NetworkStatus` event. It always uses the current timestamp.

I have a fix for this locally, but as the fix requires an update on our backend, it won't be out until Monday. If you want a temporary workaround for this, I would recommend sending a `NetworkStatus` event yourself for each `Humidity` event and making sure the timestamp is correct.

I'll update this issue when the fix is out.

**Comment by virgesmith** [comment]
wow, quick response, thanks! It's not urgent so I'm happy to wait

**Comment by vegather** [comment]
Apologies for the delay on this issue @virgesmith. I just rolled the fix out to production, so the accompanying NetworkStatus events have the same timestamp as the events you publish. This means the graph in DT Studio won't show as offline when you publish events in the past.

Note that this only applies to new events being published. The events that have already been published will still show as offline, unfortunately.

**Comment by virgesmith** [comment]
thanks @vegather all seems fine now
