### ISSUE TITLE
Unexpected behaviour creating events with pandas timestamps

### ISSUE THREAD

**Issue by virgesmith** [disruptive-technologies/python-client#79]
Hi DT,
Just spotted that if you construct an event with a pandas timestamp (e.g. from a time-indexed dataframe), the timestamp field is not populated. Here's an example:

```
import disruptive as dt
import pandas as pd
from datetime import datetime

t = datetime.utcnow()

print(t, type(t))
print(dt.events.ObjectPresent(state="PRESENT", timestamp=t)) # timestamp is correct

pt = pd.to_datetime(t)
print(pt, type(pt))
print(dt.events.ObjectPresent(state="PRESENT", timestamp=pt)) # timestamp is empty
```

Would it be possible to either make events work with pandas DateTime types, or raise an exception rather than silently blanking it? 

For now I'm using `pt.to_pydatetime()` to work round the issue

Many thanks,
Andrew

**Comment by jhgjeraker** [comment]
This is unintentional behavior and I will deal with it. 

Even though pandas is very convenient and popular for data-science applications we have no intention of including it as a dependency in our base client. I will see if I can find a generic method of turning non-datetime objects (like the pandas datetime object) into iso8601 strings that our underlying API requires. If not, I'll throw an exception.

Thanks for reporting bugs!
Johannes

**Comment by virgesmith** [comment]
Johannes,
Thanks for responding. I completely understand you don't want a dep on pandas. It seems that `pandas.DateTime` is a subclass of `datetime.datetime`, so its very odd (and so checking its a `datetime` with  `istanance` won't catch them, but `type(t) is datetime` will). I'd be interested to know how you resolve it...

**Comment by jhgjeraker** [comment]
I think I have come to an understanding of the problem.

The following snippet creates 2 touch events, one with a `datetime` timestamp and one using pandas timestamp. When printing the events, the pandas timestamp has indeed disappeared. However, when looking at the objects `_raw` attribute, which is what I send to our REST API under the hood, the timestamp value is there, just as expected.

```
>>> from datetime import datetime
>>> import pandas as pd
>>> import disruptive as dt
>>>
>>> ts = datetime.utcnow()
>>> ps = pd.to_datetime(ts)
>>>
>>> ts_event = dt.events.Touch(timestamp=ts)
>>> ps_event = dt.events.Touch(timestamp=ps)
>>>
>>> print(ts_event)
Touch(
    timestamp: datetime = 2021-08-22 11:32:09.440321,
    event_type: str = touch,
),
>>> print(ps_event)
Touch(
    timestamp: Timestamp = Timestamp(
    ),
    event_type: str = touch,
),
>>>
>>> print(ts_event._raw)
{'updateTime': '2021-08-22T11:32:09.440321Z'}
>>> print(ps_event._raw)
{'updateTime': '2021-08-22T11:32:09.440321Z'}
```

The problem seems to lie with the output formatting of my objects, more specifically with the `__str__` dunder behavior. Here's what I've discovered.

When using `pandas.to_datetime()` on a `datetime` object, the output is `pandas.Timestamp`. As you said, this is a subclass of `datetime`, which is basically what caused the silent failure here. Everything I do with `datetime` in my logic for dealing with timestamps, like converting to ISO8601 with `.isoformat()`, still works. 

```
>>> ts = datetime.utcnow()
>>> ps = pd.to_datetime(ts)
>>>
>>> isinstance(ts, datetime)
True
>>> isinstance(ps, datetime)
True
```

However, there is a difference between them. Unlike `datetime`, the `pandas.Timestamp` is a class, but a class with no attributes (by default). Therefore, in the generic `__str__` dunder I've written, which checks if a variable is a class object, the output is as you saw, empty. 

The fix is, fortunately, very simple. When recursively printing all attributes in an object, when checking if an attribute is a class, i also check if that class is an instance of `datetime`.

```
# line 59 in outputs.py.
if hasattr(val, '__dict__') and not isinstance(val, datetime):
    # print class attributes recursively.
else:
    # Now pandas timestamps are printed here as a pure string.
```

Now, the output of the first snippet should be as follows.

```
# Datetime event.
ObjectPresent(
    state: str = PRESENT,
    timestamp: datetime = 2021-08-22 11:55:50.312554,
    event_type: str = objectPresent,
)

# Pandas timestamp event.
ObjectPresent(
    state: str = PRESENT,
    timestamp: Timestamp = 2021-08-22 11:55:50.312554,
    event_type: str = objectPresent,
)
```

I've pushed the update to the branch `timestamp-format-bugfix`. Please have a look and report back if this makes sense to you, or if I've misunderstood the problem.

**Comment by virgesmith** [comment]
Thanks - I see its only a formatting issue, which is easily demonstrated (and I should have spotted this):

```
...
pt = pd.to_datetime(t)
print(pt, type(pt))
e = dt.events.ObjectPresent(state="PRESENT", timestamp=pt)
print(e)  # timestamp is empty
print(e.timestamp) # timestamp as expected
```
Happy with your change... got to go an meet Uwe for lunch now,,, Thanks for your help
